// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeu0zJbsfE6Ng6FROZ9LuJ1K7ByIiZQb0',
    appId: '1:136324996533:web:08b0be6cad81672b984dfc',
    messagingSenderId: '136324996533',
    projectId: 'teamcash-83a6e',
    authDomain: 'teamcash-83a6e.firebaseapp.com',
    storageBucket: 'teamcash-83a6e.firebasestorage.app',
    measurementId: 'G-3ZJQYKQ2D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcGPUDUQyXIbgjwU3ZtGYBT7XR4iAOLEc',
    appId: '1:136324996533:android:e531b37ec9ae615a984dfc',
    messagingSenderId: '136324996533',
    projectId: 'teamcash-83a6e',
    storageBucket: 'teamcash-83a6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3a2Ozy1gsFX65c64EqcosI22uTY4ZSRY',
    appId: '1:136324996533:ios:cb7ae2867b264834984dfc',
    messagingSenderId: '136324996533',
    projectId: 'teamcash-83a6e',
    storageBucket: 'teamcash-83a6e.firebasestorage.app',
    iosBundleId: 'com.example.teamcash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3a2Ozy1gsFX65c64EqcosI22uTY4ZSRY',
    appId: '1:136324996533:ios:cb7ae2867b264834984dfc',
    messagingSenderId: '136324996533',
    projectId: 'teamcash-83a6e',
    storageBucket: 'teamcash-83a6e.firebasestorage.app',
    iosBundleId: 'com.example.teamcash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeu0zJbsfE6Ng6FROZ9LuJ1K7ByIiZQb0',
    appId: '1:136324996533:web:5155cabd0e4bcba5984dfc',
    messagingSenderId: '136324996533',
    projectId: 'teamcash-83a6e',
    authDomain: 'teamcash-83a6e.firebaseapp.com',
    storageBucket: 'teamcash-83a6e.firebasestorage.app',
    measurementId: 'G-V28M84EQEQ',
  );
}
